### PR TITLE
Change notes.txt files to README.md files

### PR DESCRIPTION
**Pull request by dealingwith**
Updates the notes files in each section folder to README.md files that will display nicely in GitHub. 

Also updates some formatting to be more markdowny.

### CODE REVIEW

**Comment by dealingwith** [comment]
Other non-markdown formatting updates:

* remove extra carriage returns
* remove extra spaces between sentences
* remove "here" in "see here [link]"
* a couple of grammatical corrections

I tried to make as few changes as possible that might impact the meaning of the text. My goal is simply readability, specifically on GitHub.

Background: We ([Minecraft U](http://minecraftu.org)) are hoping to use a bunch of these examples in our Java modding curriculum, either straight-up or adapting them for our audience (late elementary and middle-school students). We'll probably use the GitHub repository directly (our fork) and just have them read straight from the GitHub pages. These changes will make that easier.

@TheGreyGhost the question is, are these changes useful to you, and/or work with your process of documenting these examples?

I also know the diffs here aren't helpful to see what changes were made, as I had to rename the files first. I've used separate commits for each section for now, but assume you'll want me to squash into a single commit should you accept these changes.

I'm also probably going to open a separate PR for updates to the main README and ReadMeFirst.txt (they seem redundant?)...

**Comment by TheGreyGhost** [comment]
Howdy

Keen, thanks for these!

I'll review them in the next day or so and (more likely than not) merge them straight in.

I'm about to start work on this again after a long break... fix a couple of bugs and then update for 13 including updating the various notes (some of the hints/tips are probably broken/out of date now)

If you are keen to contribute in other ways eg further examples or fixing problems with these examples, you'd be very welcome!

Cheers
  TGG

**Comment by dealingwith** [comment]
I'll squash these into a single commit tonight.

I certainly hope we'll be able to contribute further!

**Comment by dealingwith** [comment]
Ok, squashed into a single commit!

**Comment by TheGreyGhost** [comment]
Thanks dude, that's much better.

**Pull request merged**
