### PR TITLE
.gitignore, and script permissions fix

### PR DESCRIPTION
**Pull request by Lohoris**
Created a `.gitignore` to ignore all the file and directories generated by gradlew.

Also, added execute permissions for gradlew bash script, and renamed to `gradlew.sh`.

### CODE REVIEW

**Comment by dreadnaut** [comment]
@TheGreyGhost uh, could you explain why this is being closed?

Pull requests being closed without a comment can be off-putting for contributors :slightly_frowning_face:

**Comment by TheGreyGhost** [comment]
Hi Dreadnaut

Thanks for the feedback, you're right I should add a comment.  I closed it because of its age and because it has been superceded by the next Forge MDK (the gradlew and gitignore are copied straight from the MDK)

Cheers
  TGG

**Comment by dreadnaut** [comment]
Thank you for the explanation, and your work on MbE!

**Comment by TheGreyGhost** [comment]
No worries, you're welcome :)

**Pull request closed without merging**
