### PR TITLE
add new sections to MBE

### PR DESCRIPTION
**Pull request by dealingwith**
This adds five new sections to MinecraftByExample:

- mbe07_block_behavior
- mbe09_ore_spawning
- mbe10_tool_simple
- mbe16_item_food
- mbe17_block_crops

[Ask](https://github.com/TheGreyGhost/MinecraftByExample/pull/51#issuecomment-491850513) and ye shall receive! 😄 

These are some new sections we needed for our Minecraft U curriculum. Hopefully, they're all self-explanatory in terms of what they're doing/demonstrating. 

## Notes

* The READMEs are bare-bones. I can try to find time to expand them as part of this PR, or submit a follow-up PR in a few weeks, once we're underway with our summer camps (things are a little crazy right now). We have written [some curriculum](https://github.com/MinecraftU/mcu-curriculum/pull/22) around these sections that _might_ be useful in a README. I say might because it is really verbose and hand-holding copy, as it's written for middle-school children.
* The gaps in your numbering scheme worked in our favor here, except for:
  * Maybe you have other ideas for what those sections should be. I haven't actually looked at all the content on your site. 😬 
  * mbe10_tool_simple, which didn't have a different logical spot. I started with a `10_2` scheme but that didn't feel right, so I just created a second `mbe10` section. We could just move that example into the main `mbe10` folder, but for our students, I felt it was clearer to have a separate folder.
* Made as few changes to existing code as possible:
  * Removed some extra `imports`
  * Added to `build.gradle` to fix IntelliJ issues (our students will be using IntelliJ CE)

### CODE REVIEW

**Comment by dealingwith** [comment]
@atvaccaro I noticed that mbe17_block_crops still needed some love...pushed what I got done tonight, still a WIP...

**Comment by TheGreyGhost** [comment]
howdy
Great! thanks very much for that!

Please let me know when you think it's ready for merge, I'll have a browse in the meantime and let you know if there's anything that doesn't seem right.

I'm not too worried about the numbering scheme, there are rough groupings to help organise by theme but it's not likely to be confusing.  your mbe10_2_tool_simple would be fine or you could use mbe10a_tool_simple as well.  The main idea with the separate sections was to make each example as self-contained as possible, i.e. to give a very clear visual picture of what components are needed to get that particular feature working, with no links at all to any other example.

I've had some ideas for other sections which I never got to, these include

Entities
  basic entity that can be spawned and disappears after a certain time
  missile entity
  entity rendering / techne -based / animation
  entity with basic AI
  - use of datawatchers

Sound
  - point and continuous sound effects

Terrain generation

Generate a new dimension

Different rendering modes

Miscellaneous
  best practice error logging 

Places to store extra data....
WorldSavedData

**Comment by TheGreyGhost** [comment]
Forgot to mention - I'm about to start updating for 1.13 although I believe the Forge guys are probably going to skip over it directly to 1.14.

One of the most pervasive changes will probably be changing some (or most?) of the examples to the new block/item registration system using annotations instead of explicitly registering them.  I deliberately didn't do that change for 1.12 because it was a bit new at the time, but it should have been bedded down properly by now (I hope).  I plan to leave the old registration method in there for reference as well.

**Comment by atvaccaro** [comment]
That sounds like an awesome change; the current registration is very cumbersome.

**Comment by atvaccaro** [comment]
Where do you get your information for version changes? Or is it trial-and-error?

**Comment by dealingwith** [comment]
Ok we just removed `17`, so this should be good for review now.

**Comment by dealingwith** [comment]
Forgot some deletions, standby...

**Comment by dealingwith** [comment]
I'll squash these as well once it's _ready_ ready

**Comment by dealingwith** [comment]
Ok fixed and squashed the new commits! Ready for 🚀

**Comment by dealingwith** [comment]
@TheGreyGhost any idea of if/when you might merge these into master?

**Comment by TheGreyGhost** [comment]
hi
sorry for the complete silence, I've been working on another project in the meantime
I think the pull request needs a reasonable amount of time to make it align with the rest of MBE, in particular in some cases I want to enhance the example to make it more instructive.
I still plan to do it, but I think it will take me several weeks to complete.
cheers
 TGG

**Comment by dealingwith** [comment]
Cool, thanks for the update!

**Pull request merged**
